//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upb.mape.broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments_mapers
    {
        public decimal id { get; set; }
        public decimal idMaper { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public decimal value { get; set; }
    
        public virtual maper maper { get; set; }
    }
}
