//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upb.mape.broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class date
    {
        public decimal id { get; set; }
        public decimal idClient { get; set; }
        public decimal idMaper { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.TimeSpan> hour { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
        public virtual maper maper { get; set; }
    }
}
